FROM node:22-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install all dependencies
RUN npm install

# Copy application source code
COPY . .

# NOTE: If using Prisma, you can uncomment these lines to generate Prisma Client on container start/build
# ENV DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy"
# RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
